name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install pandoc

      - name: Install and Build ğŸ”§
        run: |
          mkdir dist
          touch dist/.nojekyll
          cp docs/*.css dist/
          cp -r docs/img/ dist/img/
          for file in docs/*.md; do
            name=$(basename "$file" .md)
            pandoc "$file" -o "dist/$name.html"
          done
          for file in dist/*.html; do
            name=$(basename "$file" .html)
            sed -i -e '1s|^|<meta name="viewport" content="width=device-width, initial-scale=1">\n<link rel="stylesheet" href="./github-markdown.css">\n|' "dist/$name.html"
          done

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: docs
